apiVersion: v1
kind: Secret
metadata:
  name: {{ include "jarvis-tp-link-hs-110-exporter.fullname" . }}
  labels:
    {{- include "jarvis-tp-link-hs-110-exporter.labels" . | nindent 4 }}
type: Opaque
data:
  keyfile.json: {{ .Values.secret.gcpServiceAccountKeyfile | toString | b64enc }}